### ISSUE TITLE
Very broken - add same item -get falls over

### ISSUE THREAD

**Issue by daverathbone** [erwinkulasic/Cakebase#6]
**Issue.  JSON file (array) currupts with same data.**

**Background:**
First you must have a empty file that exists before you start - can live with this e.g. users.json
Nice to have if it makes it. - just saves me having to do that before any call's to cakebase
I think you have tried fixing this...  but  no new file is made.

`
const users = require('cakebase')('./users.json')
 `

Then I put some data in:-
```

       for( i=0;i<1000;i++){
		tobj.id=i;
		await users.set(tobj);
	}


```
I  had to wrapper all calls to the functions with async  and await.
This is also fine.  As its one of the main ways you can fully handle promise based file call's.

This is my main reason for using this simple  JSON database, for just using async read /write.
as sync read/writes blocks the main worker thread in node.js, when on a busy express server application.
With sync based file handling found on big and bloated famous JSON based databases.

Having driven "set(obj)" in a for loop making the default JSON data, the file looks fine.
Just an array, with your keywords and values in - also great. will work for 90% use cases.

```
[{"id":0,"username":"Mike","email":"any@loadsOfmail.com"},{.....}]

```
**The bug.**
If you use set(obj)  again with the same data, it MUST not put it into the JSON array again.
As this will mean you have two(or more) records of the same value. 
Which one do you update....?  
Further more on using get(obj) it now gets two arrays for every new get(obj)........? (new bug)

Only update(obj) should allow change - which should onlly allow object values to change  with same object keys created by set(obj)

I thank you for fixing the last bug - as I imagine time coding is all done in your spare time.
but this update has broken  the last methord of using Cakebase - which means users/myself  having to rewrte functions.
But happy if the new code / format fixes the issues.

**Here is my code  that shows the issue;-**

```

//  if file user.json does not exist Make the file.....
const users = require('cakebase')('./users.json')


//  Still have to call with aysnc in order for await for the promise
async function main() {  // this is ok ...
	let tobj={};
	tobj.id=0;
	tobj.username="Mike";
	tobj.email="any@loadsOfmail.com";
	let i;

	for( i=0;i<1000;i++){
		tobj.id=i;
		await users.set(tobj);
	}

	// Should not be possible to add item into JSON array with set
	tobj.id=1;
	await users.set(tobj);   // bug JSON array now has to id.1's

	// This then breaks get
	const item= await users.get(tobj => tobj.id === 2);
	console.log(item);
}

main();
```

Console.log showing get(obj) having problems...
```
C:\nodecv>node DataTests.js

[
  { id: 2, username: 'Mike', email: 'any@lotsofmail.com' },
  { id: 2, username: 'Mike', email: 'any@lotsofmail.com' }
]

```

JSON file ...
```
{"id":0,"username":"Mike","email":"any@loadsOfmail.com"},
{"id":1,"username":"Mike","email":"any@loadsOfmail.com"},
.....
{"id":999,"username":"Mike","email":"any@loadsOfmail.com"},
{"id":1,"username":"Mike","email":"any@loadsOfmail.com"}]

```

Many thanks again for your time on this - will still use Cakebase
which is ideal for small user base login JSON or M2M puting in live events.
Small and simple is always the way to go.....

**Comment by erwinkulasic** [comment]
hello @daverathbone 

to simplify things here, the following points cause a problem.

- [x] When initializing Cakebase an empty file should be created
- [x] Should be able to set a whole array 
- [ ] Objects are available twice in json array

Duplicates is a more difficult problem, it is conditional on the situation.

- Do I store user data
- Do I store important analysis data for tables and charts
- and much more

The problem is how can I guarantee that no data will be lost?
I can't just solve a problem like that, I have to think about it.

Thank you for your help
have a nice day

**Comment by erwinkulasic** [comment]
The user should decide for himself how to handle his data.
